"""
OrbitMech: Autonomous Orbital Mechanics & Astrodynamics Trajectory Optimization Engine.
Pure Python standard library implementation with zero external dependencies.
"""

from orbitmech.types import (
    Vector3,
    StateVector,
    CelestialBody,
    ClassicalOrbitalElements,
    OrbitType,
    EARTH,
    SUN,
    MOON,
    MARS,
    VENUS,
    JUPITER,
    AU_KM,
    SPEED_OF_LIGHT_KMS,
)
from orbitmech.kepler import (
    state_to_orbital_elements,
    orbital_elements_to_state,
    solve_kepler_equation,
    propagate_keplerian,
    true_to_eccentric_anomaly,
    eccentric_to_true_anomaly,
    eccentric_to_mean_anomaly,
)
from orbitmech.lambert import (
    stumpff_c2,
    stumpff_c3,
    propagate_universal,
    solve_lambert,
    LambertSolution,
)
from orbitmech.propagator import (
    PerturbationConfig,
    SpacecraftProperties,
    compute_acceleration,
    propagate_symplectic_verlet,
    propagate_rk45,
    atmospheric_density_earth,
    PropagationResult,
)
from orbitmech.maneuvers import (
    hohmann_transfer,
    bi_elliptic_transfer,
    plane_change_maneuver,
    gravity_assist_flyby,
    HohmannTransferResult,
    BiEllipticTransferResult,
    PlaneChangeResult,
    GravityAssistResult,
)
from orbitmech.porkchop import (
    generate_porkchop_grid,
    PorkchopGrid,
    PorkchopPoint,
    approximate_planet_state,
)
from orbitmech.visualizer import (
    BrailleCanvas,
    Camera3D,
    render_orbit_scene,
    render_porkchop_contour,
    render_mission_telemetry_hud,
)

__all__ = [
    "Vector3",
    "StateVector",
    "CelestialBody",
    "ClassicalOrbitalElements",
    "OrbitType",
    "EARTH",
    "SUN",
    "MOON",
    "MARS",
    "VENUS",
    "JUPITER",
    "AU_KM",
    "SPEED_OF_LIGHT_KMS",
    "state_to_orbital_elements",
    "orbital_elements_to_state",
    "solve_kepler_equation",
    "propagate_keplerian",
    "true_to_eccentric_anomaly",
    "eccentric_to_true_anomaly",
    "eccentric_to_mean_anomaly",
    "stumpff_c2",
    "stumpff_c3",
    "propagate_universal",
    "solve_lambert",
    "LambertSolution",
    "PerturbationConfig",
    "SpacecraftProperties",
    "compute_acceleration",
    "propagate_symplectic_verlet",
    "propagate_rk45",
    "atmospheric_density_earth",
    "PropagationResult",
    "hohmann_transfer",
    "bi_elliptic_transfer",
    "plane_change_maneuver",
    "gravity_assist_flyby",
    "HohmannTransferResult",
    "BiEllipticTransferResult",
    "PlaneChangeResult",
    "GravityAssistResult",
    "generate_porkchop_grid",
    "PorkchopGrid",
    "PorkchopPoint",
    "approximate_planet_state",
    "BrailleCanvas",
    "Camera3D",
    "render_orbit_scene",
    "render_porkchop_contour",
    "render_mission_telemetry_hud",
]
