"""Gate-Level Mapped Netlist Data Structures and Structural Verilog Codec.

Features:
1. Physical netlist representation: cell instances, pins, nets, and connectivity.
2. Net capacitance calculation: wire parasitic capacitance + load pin capacitances.
3. Total silicon area (um^2) and static leakage power (nW) calculation.
4. Export to canonical structural Verilog netlist.
"""

from __future__ import annotations
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Set, Tuple

from .liberty import StandardCell


@dataclass
class Net:
    """Electrical net connecting driver pin to load pins."""
    name: str
    driver: Optional[Tuple[str, str]] = None  # (cell_instance, pin_name) or None if PI
    loads: List[Tuple[str, str]] = field(default_factory=list)  # [(cell_instance, pin_name), ...]
    is_primary_input: bool = False
    is_primary_output: bool = False
    wire_cap: float = 0.5  # Base wire parasitic capacitance in fF
    total_cap: float = 0.0 # Total capacitive load including pin capacitances


@dataclass
class CellInstance:
    """Instance of a standard cell in the gate-level netlist."""
    name: str
    cell_type: StandardCell
    pin_connections: Dict[str, str]  # pin_name -> net_name


class Netlist:
    """Gate-level mapped netlist container."""

    def __init__(self, name: str = "top") -> None:
        self.name = name
        self.inputs: List[str] = []
        self.outputs: List[str] = []
        self.cells: Dict[str, CellInstance] = {}
        self.nets: Dict[str, Net] = {}

    def add_input(self, name: str) -> None:
        """Register primary input port."""
        if name not in self.inputs:
            self.inputs.append(name)
        if name not in self.nets:
            self.nets[name] = Net(name=name, is_primary_input=True)

    def add_output(self, name: str) -> None:
        """Register primary output port."""
        if name not in self.outputs:
            self.outputs.append(name)
        if name not in self.nets:
            self.nets[name] = Net(name=name, is_primary_output=True)

    def get_or_create_net(self, name: str) -> Net:
        """Get or create net by name."""
        if name not in self.nets:
            self.nets[name] = Net(name=name)
        return self.nets[name]

    def add_cell(
        self,
        instance_name: str,
        cell: StandardCell,
        connections: Dict[str, str],
    ) -> CellInstance:
        """Instantiate a standard cell and link its pin connections."""
        if instance_name in self.cells:
            raise ValueError(f"Cell instance '{instance_name}' already exists in netlist")

        instance = CellInstance(
            name=instance_name,
            cell_type=cell,
            pin_connections=dict(connections),
        )
        self.cells[instance_name] = instance

        # Wire up driver and load pointers on nets
        for pin_name, net_name in connections.items():
            net = self.get_or_create_net(net_name)
            pin_def = cell.pins.get(pin_name)
            is_input = pin_def.is_input if pin_def else (pin_name in cell.inputs)

            if is_input:
                net.loads.append((instance_name, pin_name))
            else:
                net.driver = (instance_name, pin_name)

        return instance

    @property
    def total_area(self) -> float:
        """Total active silicon area in square micrometers (um^2)."""
        return sum(inst.cell_type.area for inst in self.cells.values())

    @property
    def total_leakage_power(self) -> float:
        """Total static leakage power in nanowatts (nW)."""
        return sum(inst.cell_type.leakage_power for inst in self.cells.values())

    @property
    def num_cells(self) -> int:
        return len(self.cells)

    @property
    def num_nets(self) -> int:
        return len(self.nets)

    def compute_net_capacitances(self, wire_cap_per_fanout: float = 0.3) -> None:
        """Calculate total capacitive load (fF) on every net."""
        for net in self.nets.values():
            # Wire parasitic capacitance proportional to fanout
            fanout = len(net.loads)
            total = net.wire_cap + (wire_cap_per_fanout * fanout)

            # Sum input capacitances of all driven sink pins
            for inst_name, pin_name in net.loads:
                inst = self.cells.get(inst_name)
                if inst and pin_name in inst.cell_type.pins:
                    total += inst.cell_type.pins[pin_name].capacitance
                else:
                    total += 1.0  # Default 1.0 fF

            net.total_cap = round(total, 3)

    def export_verilog(self) -> str:
        """Export structural Verilog netlist."""
        lines: List[str] = []
        lines.append(f"// Generated by LogicCraft EDA Synthesis Engine")
        ports = self.inputs + self.outputs
        lines.append(f"module {self.name} ({', '.join(ports)});")

        if self.inputs:
            lines.append(f"  input {', '.join(self.inputs)};")
        if self.outputs:
            lines.append(f"  output {', '.join(self.outputs)};")

        # Internal wires (exclude primary ports)
        internal_wires = [n for n in self.nets if n not in self.inputs and n not in self.outputs]
        if internal_wires:
            lines.append(f"  wire {', '.join(internal_wires)};")

        lines.append("")
        for inst in self.cells.values():
            conns = [f".{pin}({net})" for pin, net in inst.pin_connections.items()]
            lines.append(f"  {inst.cell_type.name} {inst.name} ({', '.join(conns)});")

        lines.append("endmodule")
        return "\n".join(lines)
