"""
Magnetic Field Topology, Flux Surface Geometry & Safety Factor Engine.

Evaluates 3D magnetic fields B(R, phi, Z) from poloidal flux surfaces psi(R, Z),
verifies Gauss's law for magnetism div(B) = 0, traces closed magnetic flux contours,
and evaluates safety factor q(psi) profiles and magnetic shear s(psi).
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from typing import List, Optional, Tuple, Union

from .equilibrium import EquilibriumProfile, GradShafranovSolver, SolovevEquilibrium


@dataclass(frozen=True)
class MagneticField:
    """Three-dimensional magnetic field vector in cylindrical coordinates (R, phi, Z)."""

    b_r: float
    b_phi: float
    b_z: float

    @property
    def magnitude(self) -> float:
        """Total magnetic field magnitude |B| in Tesla."""
        return math.sqrt(self.b_r * self.b_r + self.b_phi * self.b_phi + self.b_z * self.b_z)

    @property
    def poloidal_magnitude(self) -> float:
        """Poloidal magnetic field component B_p = sqrt(B_R^2 + B_Z^2)."""
        return math.sqrt(self.b_r * self.b_r + self.b_z * self.b_z)

    @property
    def pitch_angle(self) -> float:
        """Field line pitch angle relative to the toroidal axis: arctan(B_p / B_phi)."""
        return math.atan2(self.poloidal_magnitude, abs(self.b_phi))

    def to_cartesian(self, phi: float) -> Tuple[float, float, float]:
        """Convert cylindrical field components to Cartesian coordinates (B_x, B_y, B_z)."""
        cos_p = math.cos(phi)
        sin_p = math.sin(phi)
        bx = self.b_r * cos_p - self.b_phi * sin_p
        by = self.b_r * sin_p + self.b_phi * cos_p
        bz = self.b_z
        return bx, by, bz


class MagneticFieldEvaluator:
    """
    Evaluator for magnetic fields generated by analytical or numerical equilibria.

    Implements:
        B_R = -(1/R) * dpsi/dZ
        B_phi = F(psi) / R
        B_Z = (1/R) * dpsi/dR
    """

    def __init__(
        self,
        equilibrium: Union[SolovevEquilibrium, GradShafranovSolver],
        profile: Optional[EquilibriumProfile] = None,
    ) -> None:
        self.equilibrium = equilibrium
        self.profile = profile or EquilibriumProfile()

    def evaluate_at(self, r: float, z: float) -> MagneticField:
        """Calculate magnetic field vector (B_R, B_phi, B_Z) at cylindrical position (R, Z)."""
        if isinstance(self.equilibrium, SolovevEquilibrium):
            br, bphi, bz = self.equilibrium.magnetic_field(r, z)
            return MagneticField(br, bphi, bz)

        # Finite-difference numerical differentiation on the solver grid
        h = 1e-4
        psi_r_plus = self.equilibrium.interpolate_psi(r + h, z)
        psi_r_minus = self.equilibrium.interpolate_psi(r - h, z)
        dpsi_dr = (psi_r_plus - psi_r_minus) / (2.0 * h)

        psi_z_plus = self.equilibrium.interpolate_psi(r, z + h)
        psi_z_minus = self.equilibrium.interpolate_psi(r, z - h)
        dpsi_dz = (psi_z_plus - psi_z_minus) / (2.0 * h)

        br = -(1.0 / r) * dpsi_dz
        bz = (1.0 / r) * dpsi_dr

        psi_val = self.equilibrium.interpolate_psi(r, z)
        psi_n = self.equilibrium.normalized_flux(psi_val)
        f_val = self.profile.f_stream(psi_n)
        bphi = f_val / r

        return MagneticField(br, bphi, bz)

    def verify_divergence_free(self, r: float, z: float, h: float = 1e-4) -> float:
        """
        Verify Gauss's law for magnetism in cylindrical axisymmetric coordinates:
            div(B) = (1/R) * d(R * B_R)/dR + dB_Z/dZ = 0
        Returns the absolute residual of div(B).
        """
        # Central difference for d(R*B_R)/dR
        f_r_plus = (r + h) * self.evaluate_at(r + h, z).b_r
        f_r_minus = (r - h) * self.evaluate_at(r - h, z).b_r
        d_rbr_dr = (f_r_plus - f_r_minus) / (2.0 * h)

        # Central difference for dB_Z/dZ
        bz_plus = self.evaluate_at(r, z + h).b_z
        bz_minus = self.evaluate_at(r, z - h).b_z
        dbz_dz = (bz_plus - bz_minus) / (2.0 * h)

        div_b = (1.0 / r) * d_rbr_dr + dbz_dz
        return abs(div_b)


class SafetyFactorCalculator:
    """
    Evaluates safety factor q(psi) and magnetic shear s(psi).

    Safety factor measures the average toroidal rotations of a field line per
    single poloidal transit:
        q(psi) = (1 / 2*pi) * closed_contour_integral [ (B_phi / (R * B_p)) dl_p ]
    """

    def __init__(
        self,
        evaluator: MagneticFieldEvaluator,
        r_axis: float,
        z_axis: float,
        minor_radius_a: float = 1.0,
        kappa: float = 1.6,
    ) -> None:
        self.evaluator = evaluator
        self.r_axis = r_axis
        self.z_axis = z_axis
        self.minor_radius_a = minor_radius_a
        self.kappa = kappa

    def compute_q_at_minor_radius(self, r_minor: float, num_samples: int = 128) -> float:
        """
        Compute safety factor q for an elliptical magnetic flux contour at minor radius r_minor.

        Contour parameterized by poloidal angle theta in [0, 2*pi):
            R(theta) = R_axis + r_minor * cos(theta)
            Z(theta) = Z_axis + kappa * r_minor * sin(theta)
        """
        if r_minor <= 1e-4:
            # On-axis analytical limit: q_0 = (2 * kappa / (1 + kappa^2)) * (B_0 / (R_0 * B_p'))
            r_test = 0.05 * self.minor_radius_a
            return self.compute_q_at_minor_radius(r_test, num_samples)

        d_theta = (2.0 * math.pi) / num_samples
        line_integral = 0.0

        for k in range(num_samples):
            theta = k * d_theta
            cos_t = math.cos(theta)
            sin_t = math.sin(theta)

            r_val = self.r_axis + r_minor * cos_t
            z_val = self.z_axis + self.kappa * r_minor * sin_t

            # Tangent segment length dl_p = sqrt((dR)^2 + (dZ)^2)
            dr_dtheta = -r_minor * sin_t
            dz_dtheta = self.kappa * r_minor * cos_t
            dl_p = math.sqrt(dr_dtheta * dr_dtheta + dz_dtheta * dz_dtheta) * d_theta

            field = self.evaluator.evaluate_at(r_val, z_val)
            bp = max(1e-9, field.poloidal_magnitude)
            integrand = field.b_phi / (r_val * bp)

            line_integral += integrand * dl_p

        return abs(line_integral / (2.0 * math.pi))

    def compute_profile(self, num_points: int = 20) -> List[Tuple[float, float, float]]:
        """
        Compute radial safety factor profile [(rho_norm, q, shear), ...].

        Magnetic shear s = (r / q) * dq/dr.
        """
        results: List[Tuple[float, float, float]] = []
        dr = self.minor_radius_a / (num_points + 1)

        q_values: List[float] = []
        r_values: List[float] = []

        for i in range(1, num_points + 1):
            r_minor = i * dr
            q_val = self.compute_q_at_minor_radius(r_minor)
            q_values.append(q_val)
            r_values.append(r_minor)

        for i in range(len(q_values)):
            r_curr = r_values[i]
            q_curr = q_values[i]
            rho = r_curr / self.minor_radius_a

            # Central finite difference for dq/dr
            if i == 0:
                dq_dr = (q_values[1] - q_values[0]) / dr
            elif i == len(q_values) - 1:
                dq_dr = (q_values[-1] - q_values[-2]) / dr
            else:
                dq_dr = (q_values[i + 1] - q_values[i - 1]) / (2.0 * dr)

            shear = (r_curr / q_curr) * dq_dr if q_curr > 1e-6 else 0.0
            results.append((rho, q_curr, shear))

        return results

    def find_rational_surfaces(
        self,
        tolerances: float = 0.05,
    ) -> List[Tuple[int, int, float]]:
        """
        Locate major low-order rational surfaces q = m / n where magnetic tearing modes resonate.

        Returns list of (m, n, rho_norm).
        """
        rational_targets = [
            (1, 1),
            (3, 2),
            (2, 1),
            (5, 2),
            (3, 1),
            (4, 1),
        ]
        found_surfaces: List[Tuple[int, int, float]] = []
        profile = self.compute_profile(num_points=40)

        for m, n in rational_targets:
            target_q = float(m) / float(n)
            best_rho = None
            min_diff = float("inf")

            for rho, q_val, _ in profile:
                diff = abs(q_val - target_q)
                if diff < min_diff:
                    min_diff = diff
                    best_rho = rho

            if min_diff <= tolerances and best_rho is not None:
                found_surfaces.append((m, n, best_rho))

        return found_surfaces
